### PR TITLE
[NSA-8535] Create GET endpoint to get all user service requests

### PR DESCRIPTION
**Pull request by insacuri**

### CODE REVIEW

**Review by JaredAMarsh — COMMENTED** [review]
To answer a question I saw raised in the code, the `extend` block in the model allows you to define tables/columns to `JOIN` onto in SQL if required, so now that the `organisation` and `userServiceRequest` models are added, you'd now be able to grab the full organisation object if needed for each request in future sequelize queries 👍 [See the docs for more info!](https://sequelize.org/docs/v6/core-concepts/assocs/)

Everything else that I can see looks good, adding unit tests for nearby files as well as covering the aspects of your own code is good, as well as making sure you cover your ESLint fixes 👍

What I would ask is that you rebase your changes, you can do this by pulling the latest main branch down, going back to your branch and typing `git rebase -i main` which will allow you to squash commits together to avoid "commit more progress" type commits being listed 😄 You'd need to then `git push --force-with-lease` on your branch to push up the updated history of course.

**Review by JaredAMarsh — DISMISSED** [review]

**Review by alexplattdfe — DISMISSED** [review]
Looks good.

**Review by JaredAMarsh — APPROVED** [review]
Still looks good 👍 Great additional README change for the future 😄

**Review by alexplattdfe — APPROVED** [review]
Looks good.

**Pull request merged**
