### PR TITLE
[NSA-8534] Patch user service request endpoint

### PR DESCRIPTION
**Pull request by insacuri**

### CODE REVIEW

**Review by AMcCartneyMTH — DISMISSED** [review]
Not a blocker, but 'bad times' appearing for the error message in a number of the tests might be something to consider changing - I don't mind it personally.

**Review by alexplattdfe — APPROVED** [review]
Looks good to me

**Review by AMcCartneyMTH — APPROVED** [review]
LGTM. Tested locally, all unit tests pass.

**Review by alexplattdfe — APPROVED** [review]
LGTM

**Pull request merged**
